#!/usr/bin/env python

import argparse
import logging
import sys

from cbopensource.connectors.taxii.bridge import runner

logging.basicConfig(stream=sys.stdout, level=logging.INFO, format='%(asctime)s %(message)s')
logger = logging.getLogger(__name__)


def build_cli_parser():
    parser = argparse.ArgumentParser()

    #
    # for each supported output type, add an option
    #
    parser.add_argument("-c", "--config",
                        action="store",
                        dest="config_path",
                        help="CBTaxii config file")

    parser.add_argument("-e", "--export-dir",
                        action="store",
                        dest="export_dir",
                        help="Export mode")

    parser.add_argument("-i", "--import-dir",
                        action="store",
                        dest="import_dir",
                        help="Parse XML from files")

    parser.add_argument("-d", "--debug",
                        action="store_true",
                        help="Enter debug mode")

    return parser


if __name__ == "__main__":

    parser = build_cli_parser()
    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)

    if not args.config_path:
        logger.error("Missing config file path")
        parser.print_help()
        sys.exit(-1)

    runner(args.config_path, args.debug, args.import_dir, args.export_dir)
