#!/usr/bin/env python
# coding: utf-8
# Copyright © 2014-2020 VMware, Inc. All Rights Reserved.
################################################################################

import os
import sys

import yaml

yaml.warnings({'YAMLLoadWarning': False})

from cbopensource.connectors.taxii import bridge, version


################################################################################
# Begin main
################################################################################

if __name__ == "__main__":
    name = "cb-taxii-connector"

    # set the path to the CA certificate PEM file to our local cache
    cacert_pem_path = "/usr/share/cb/integrations/cb-taxii-connector/cacert.pem"
    cacert_pem_path2 = "/etc/cb/integrations/taxii/cacert.pem"
    if os.path.isfile(cacert_pem_path) or os.path.isfile(cacert_pem_path2):
        os.environ["REQUESTS_CA_BUNDLE"] = cacert_pem_path if os.path.isfile(cacert_pem_path) else cacert_pem_path2

    daemon = bridge.CarbonBlackTaxiiBridge(name, "/etc/cb/integrations/taxii/connector.conf")

    # ARGV: <"start"|"stop"|"restart"|"version">
    #       <"write"> <filename>
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'version' == sys.argv[1]:
            print(f"{name} - version {version.__version__}")
        else:
            print(f"Unknown command: {sys.argv[1]}")
            sys.exit(2)
    elif len(sys.argv) == 3:
        if 'write' == sys.argv[1]:
            json = daemon.perform_continuous_feed_retrieval(False)
            with open(sys.argv[2], 'w') as f:
                f.write(json)
        else:
            print(f"Unknown command: {sys.argv[1]}")
            sys.exit(2)

    else:
        print("Usage: %s start|stop|restart|version|write <filename>" % sys.argv[0])
        sys.exit(2)
